[[footer]]
name = "Accueil"
url = ""
weight = "1"
[[footer]]
name = "À propos"
url = "about/"
weight = 2
[[footer]]
name = "Tarification"
url = "pricing/"
weight = "3"
[[footer]]
name = "Contact"
url = "contact/"
weight = "4"
[[main]]
name = "Accueil"
url = ""
weight = 1
[[main]]
name = "À propos"
url = "about/"
weight = 2
[[main]]
name = "Tarification"
url = "pricing/"
weight = "3"
[[main]]
name = "Contact"
url = "contact/"
weight = "4"
