address_descriptors = false
author = "Themefisher"
copyright = "Site créé par Dorian TESTA (mailto:doriantesta@yahoo.fr)"
custom_script = ""
description = "This is meta description"
email = "test@email.com"
favicon = "images/favicon.png"
google_tag_manager = ""
image = "/images/Logo.PNG"
location = "13 cours Pierre Puget 13006 Marseille"
logo = "images/logo V1.png"
logo_text = "Chloé FABIAN"
logo_width = "55px"
navbar_fixed = false
phone = "07 50 50 50 50"
recaptcha_site_key = "xxx-xxxxxxxxxxxxxxxxxxxxxxxx"
social = []
[baidu]
analytics_id = ""
enable = false
[contact.form]
action = "#"
enable = true
success_image = "images/paper-plane.svg"
use_netlify = true
use_recaptcha = true
[cookies]
button = "J'accepte !"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[counter]
enable = false
username = ""
[gmap]
enable = true
gmap_api = "AIzaSyAnLWT024Pw0TmymtD1hH3q20Zk_bNAtA4"
map_latitude = "43.2904462"
map_longitude = "5.3736582,18"
map_marker = "images/marker.png"
[matomo]
enable = false
id = ""
url = ""
[navigation_button]
enable = true
label = "get a quote"
link = "contact"
[plausible]
domain = ""
enable = false
[preloader]
enable = true
preloader = ""
[site_verification]
baidu = ""
bing = ""
google = ""
[widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
